name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # या master, आपकी मेन ब्रांच का जो भी नाम हो

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # यह इस ब्रांच पर बिल्ड को भेजेगा
          folder: dist # build होकर कोड इस फोल्डर में आता है